output-class: CoreLocalizations
synthetic-package: false
arb-dir: lib/l10n
output-dir: ./lib/l10n/generated/
template-arb-file: intl_vi.arb
output-localization-file: core_localizations.dart
resource-file: lib/l10n/localizations.csv
format: true