name: core
description: A new Flutter package project.
version: 3.24.0

publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  #language
  flutter_localizations:
    sdk: flutter
  sprintf: 7.0.0

  #base
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  shared_preferences: ^2.0.7
  get_it: ^7.2.0
  injectable: ^2.4.4
  intl: ^0.19.0

  #utils
  logger: ^1.0.0
  date_format: ^2.0.2
  connectivity_plus: ^6.0.5
  permission_handler: ^11.0.1
  uuid: any
  timeago: ^3.1.0
  mime: ^1.0.2
  dartx: ^1.1.0
  equatable: ^2.0.5
  fl_utils:
    path: ../plugins/fl_utils
  event_bus: ^2.0.0

  #Hive
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  #JSON
  json_annotation: 4.8.1
  phone_numbers_parser: ^7.0.2
  flutter_multi_formatter: ^2.12.1
  freezed: ^2.4.5

  #ui
  fluttertoast: 8.2.8
  another_flushbar: ^1.12.30
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.3
  dotted_border: ^2.0.0
  webview_flutter: ^4.0.5
  video_thumbnail: ^0.5.2
  video_player: ^2.4.5
  chewie: ^1.3.3
  table_calendar: ^3.0.7
  flutter_widget_from_html: ^0.15.2
  photo_view: ^0.15.0
  pdf_render: ^1.4.12
  auto_size_text: ^3.0.0
  flutter_swipe_action_cell: ^3.1.2
  dropdown_button2: ^2.0.0
  expandable: ^5.0.1
  fl_ui:
    path: ../plugins/fl_ui
  fl_theme:
    path: ../plugins/fl_theme
  fl_media:
    path: ../plugins/fl_media
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  retrofit_generator: ^9.1.2
  hive_generator: ^2.0.1
  json_serializable: 6.7.1
  injectable_generator: ^2.6.2
  module_generator:
    path: ../tools/module_generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
