arb-dir: lib/l10n
template-arb-file: intl_vi.arb
output-localization-file: app_localizations.dart
resource-file: lib/l10n/localizations.csv

output-dir: ./lib/l10n/generated/
output-class: AppLocalizations
synthetic-package: false
format: true