name: google_form
description: Flutter Application

version: 1.0.0+1
version_staging: 1.0.0+1
version_prod: 1.0.0+1

publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # language
  flutter_localizations:
    sdk: flutter

  # base
  flutter_native_splash: ^2.2.8
  core:
    path: ../../core

  # utils
  date_format: ^2.0.2

  # data
  freezed: ^2.4.5

  #ui
  fl_chart: 0.69.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  retrofit_generator: ^9.1.2
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.2
  module_generator:
    path: ../../tools/module_generator

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/
    
  fonts:
    - family: SF-Pro
      fonts:
        # Light
        - asset: assets/fonts/SFProText-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/SFProText-LightItalic.ttf
          style: italic
          weight: 300
        
        # Regular
        - asset: assets/fonts/SFProText-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/SFProText-RegularItalic.ttf
          style: italic
          weight: 400

        # MediumBold
        - asset: assets/fonts/SFProText-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/SFProText-MediumItalic.ttf
          style: italic
          weight: 500

        # SemiBold
        - asset: assets/fonts/SFProText-Semibold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/SFProText-SemiboldItalic.ttf
          style: italic
          weight: 600

        # Bold
        - asset: assets/fonts/SFProText-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/SFProText-BoldItalic.ttf
          style: italic
          weight: 700

        # Heavy
        - asset: assets/fonts/SFProText-Heavy.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/SFProText-HeavyItalic.ttf
          style: italic
          weight: 800

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
